# Generated by Django 4.2 on 2025-06-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areacode', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=80)),
                ('mac_address', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField()),
                ('vehicle_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('licenseplate_no', models.CharField(max_length=50, null=True)),
                ('vehicle_image', models.ImageField(blank=True, default=None, null=True, upload_to='Vehicle_images/')),
                ('license_plate_image', models.ImageField(blank=True, default=None, null=True, upload_to='License_plate_images/')),
                ('stationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.station')),
            ],
        ),
    ]
