# Generated by Django 4.2 on 2025-06-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='licenseplate_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='violation_count',
            field=models.IntegerField(default=0),
        ),
    ]
