# Generated by Django 4.2 on 2025-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_vehicle_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='speed_limit',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='record',
            name='license_plate_image',
            field=models.ImageField(blank=True, default='test_images/licenseplate_0_0.jpg', null=True, upload_to='License_plate_images/'),
        ),
    ]
