# Generated by Django 4.2 on 2025-06-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_station_speed_limit_alter_record_license_plate_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="email_id",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name="station",
            name="speed_limit",
            field=models.IntegerField(default=30),
        ),
    ]
