# Generated by Django 4.2 on 2025-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_vehicle_email_id_alter_station_speed_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="email_id",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
