# Generated by Django 4.2 on 2025-06-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0006_alter_vehicle_email_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="email_id",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
