# Generated by Django 4.2 on 2025-07-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0008_alert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="speed_limit",
            field=models.IntegerField(default=10),
        ),
    ]
